### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by SalmonDE** [SalmonGER/StatsPE#1]
# HIGH PRIORITY
- [x] /fixtable
- [ ] Add an API (Status: Assignee: @robske110, Progress: Concept making...)
- [ ] Async Update Check
- [x] Configurable messages
## General:
- [x] JSON Support
- [x] MySQL Support
- [x] Make some statistics not show on /stats (according to config.yml)
- [x] Create an updater
- [x] FloatingStats
- [ ] Fix FloatingStats being in every level (Status: Asignee: @robske110, Progress: WIP (25%))
## What the plugin should save:
- [x] Playername
- [x] Online
- [x] ClientID
- [x] Client Secret
- [x] XBoxAuthenticated
- [x] LastIP
- [x] FirstJoin
- [x] LastJoin
- [x] Joincount
- [x] Killcount
- [x] Deathcount
- [x] K/D
- [x] Kickcount
- [x] Onlinetime
- [x] BlocksBreaked
- [x] BlocksPlaced
- [x] ChatMessages
- [x] Fishcatchcount
- [x] Bedcount (When player enters a bed)
- [x] Eatcount
- [x] Craftcount
- [x] Items dropped
## Additional:
- [x] "/stats [Player]" command
- [ ] /statstop (/top is a command already used by EssentialsPE)

**Comment by SalmonGER** [comment]
K/D perhaps

**Comment by SalmonGER** [comment]
@SalmonGER And categories (different colours)

**Comment by SalmonGER** [comment]
Is authenticated with XBox

**Comment by RoofyManStar** [comment]
Add floating status /top , @SalmonGER NOW!!!!!

**Comment by RoofyManStar** [comment]
@SalmonGER

**Comment by padrone21** [comment]
player online and max player

**Comment by padreon** [comment]
player online, max player, money

**Comment by Aericio** [comment]
@padrone21 StatsPE is for player stats, not tracking players online.

**Comment by SalmonDE** [comment]
@padrone21 A simple Query request could get you the latest information about online and max players, Money is on the ToDo list. Thanks for your suggestions! ;)

**Comment by robske110** [comment]
Updated

**Comment by Aericio** [comment]
Money is how? How much money they earned / spent? How much money they gave?

**Comment by daniktheboss** [comment]
I think like current / max / spent

**Comment by Aericio** [comment]
@daniktheboss Thats what I think

**Comment by daniktheboss** [comment]
Would be cool XD

**Comment by Aericio** [comment]
Max / spent is fine I think, no need for current currency... /money or /bal could do that

**Comment by daniktheboss** [comment]
True

**Comment by NycuRO** [comment]
@SalmonGER Salami,you can add in Online = time on this server. Not yes/no

**Comment by SalmonGER** [comment]
@NycuRO uhm OnlineTime

**Comment by NycuRO** [comment]
@SalmonGER Yes,onlinetime

**Comment by NycuRO** [comment]
@SalmonGER You speak in TODO *this issue* : Onlinetime is implemented. But isn't

**Comment by NycuRO** [comment]
Now work

**Comment by ghost** [comment]
@SalmonGER Salmon.you can create one Task for FloatingStats please?

E.g. In floatingstats show OnlineTime: 18 sec , 19 sec , 20 sec 💃 

One task for live floatingstats ,not for re-enter again again on server for update

**Comment by Aericio** [comment]
Make that optional, pleaaase.

**Comment by SalmonDE** [comment]
Actually I'm still hoping robske would begin to explain me how his system works.

**Comment by robske110** [comment]
Which?

**Comment by SalmonDE** [comment]
@robske110 Making the floating text particles invisible

**Comment by RocoWayne** [comment]
can be used in pocketmine?

**Comment by SalmonGER** [comment]
@RocoWayne I didn't test yet but if you encounter any issues tell us! :)

**Comment by inxomnyaa** [comment]
it can

**Comment by ghost** [comment]
@SalmonGER Add money to TODO list :)

**Comment by SalmonDE** [comment]
@NycuRO Well, money is usually already saved by the money plugin

**Comment by ghost** [comment]
@SalmonGER In floatingstatus man.

**Comment by ghost** [comment]
@SalmonGER Wann wird der command /top in das Stats Plugin hinzugefügt?

**Comment by Aericio** [comment]
#DemandARewrite
