### ISSUE TITLE
TODO, Features?

### ISSUE THREAD

**Issue by NycuR0** [SalmonGER/StatsPE#78]
![image](https://user-images.githubusercontent.com/21292815/32745132-6ff19e52-c8ba-11e7-8a18-305905894d5c.png)

![image](https://user-images.githubusercontent.com/21292815/32745151-80023ee6-c8ba-11e7-836f-fcfd97588255.png)

- [ ] 1) Can you add modals?
- [ ] 2) Can you add API for change default language of server? (And option)
- [ ] 3) Profile?
- [ ] 4) FloatingStats uses one function with name "CENTER" ,like that?

![image](https://user-images.githubusercontent.com/21292815/32745276-eb9bcb68-c8ba-11e7-8697-be0ee604dbb4.png)

This is superBar by poggit-ortography.

(Uses CENTER function, if you don't watch. (Don't start any line from start, and it's arranged according to how long the writing is).

If you don't like to add to StatsPE, just use ProfilePE (Create new Plugin) 👍

**Comment by Aericio** [comment]
1) What the fuck is a modal?
2) It should be customizable via config.yml, why should an api exist to change the language? For individual user language settings?
3) Profiles in StatsPE are completely useless, so no on profile.
4) ok.

**Comment by NycuR0** [comment]
@Aericio 
1. Modal it's Packet for create this "GUI"
2. Gimme methods how get Number of Kills, deaths , and others. I don't find any API to this plugin.
Just create functions for getKills, getDeaths and etc. 
3. I think @SalmonDE want 👍 
4. Ok, i wait add center 👍

kiss salami <3

**Comment by SalmonDE** [comment]
@NycuR0 via the entry system you can get kills and deaths. I'm currently working on splitting entries from the data provider in statspe 4.x.x

**Comment by NycuR0** [comment]
@SalmonDE What entry system?

**Comment by ItsBlueey** [comment]
How did you get StatsPE into SuperBar? I need it show kills, deaths and kdr..

**Comment by Aericio** [comment]
Superbar needs to support this plugin first.

**Comment by ghost** [comment]
@Aericio @SalmonDE can you add ping?

**Comment by Aericio** [comment]
@NycuRO project is dead lmao

**Comment by ghost** [comment]
revive it @Aericio

**Comment by Aericio** [comment]
@NycuRO no lol

**Comment by Aericio** [comment]
SalmonDE planned on rewriting it, but he has no time / motivation / care to rewrite this right now, so it's dead for the time being.
